# Bug

This repo can be used to replicate an error in the `azure-ai-projects-1.1.0b4` SDK when running multiple cloud evals.

The error is error:

**Error during evaluation for run ID 1c8a7203-5c34-4a97-87c9-d599261017cb: (InternalError) I/O operation on closed file.**

![alt text](image.png)

## Run
pip install --pre -r requirements.txt